### ISSUE TITLE
frontendinterfaces Build Error 

### ISSUE THREAD

**Issue by hoalu1** [RedhawkSDR/frontendInterfaces#4]
When building , I receive the following errors:
Src/java/FRONTEND/GPSInfo.java:44 error: package BULKIO does not exist
Src/java/FRONTEND/GPSInfo.java:47 error: package CF does not exist

**Comment by jirwin-geon** [comment]
Is this when building the frontendInterfaces library itself, or something else? Which version of REDHAWK?

The compiler's classpath is missing `CFInterfaces.jar` and `BULKIOInterfaces.jar`, which are normally added to the compile command automatically.

**Comment by jirwin-geon** [comment]
This repository is deprecated; it's been consolidated into https://github.com/RedhawkSDR/core-framework. If you still experience this problem with the current version, you can open an issue against that repository.

**Comment by quray1985** [comment]
I have the same errors. How can I fix these errors?
